# Tipos de variaveis ------------------------------------------------------

col_numericas <- c("faixa_etaria",
                   "faixa_hora_contrat",
                   "faixa_remun_dezem_sm",
                   "faixa_remun_media_sm",
                   "faixa_tempo_emprego",
                   "escolaridade_apos_2005",
                   "qtd_hora_contr",
                   "idade",
                   "qtd_dias_afastamento",
                   "vl_remun_dezembro_nom",
                   "vl_remun_dezembro_sm",
                   "vl_remun_media_nom",
                   "vl_remun_media_sm",
                   "tempo_emprego",
                   "vl_rem_janeiro_cc" ,
                   "vl_rem_fevereiro_cc",
                   "vl_rem_marco_cc",
                   "vl_rem_abril_cc" ,
                   "vl_rem_maio_cc" ,
                   "vl_rem_junho_cc" ,
                   "vl_rem_julho_cc",
                   "vl_rem_agosto_cc",
                   "vl_rem_setembro_cc",
                   "vl_rem_outubro_cc",
                   "vl_rem_novembro_cc"
)

cal_fatores <- c("causa_afastamento_1",
                 "causa_afastamento_2",
                 "causa_afastamento_3",
                 "motivo_desligamento",
                 "cbo_ocupacao_2002",
                 "cnae_2_0_classe",
                 "cnae_95_classe",
                 "vinculo_ativo_31_12",
                 "ind_cei_vinculado",
                 "ind_simples",
                 "mes_admissao",
                 "mes_desligamento",
                 "nacionalidade",
                 "natureza_juridica",
                 "ind_portador_defic",
                 "raca_cor",
                 "regioes_adm_df",
                 "cnae_2_0_subclasse",
                 "sexo_trabalhador",
                 "tamanho_estabelecimento",
                 "tipo_admissao",
                 "tipo_estab",
                 "tipo_vinculo",
                 "ibge_subsetor"
)
